### ISSUE TITLE
Primary toggle component styling

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly#2713] opened 2020-02-14 11:07 UTC
As per previous conversations at https://github.com/patternfly/patternfly-next/issues/1872#issuecomment-558823014 and at https://github.com/patternfly/patternfly-design-kit/issues/159, I'm opening a new issue to discuss the possible restyling of the [Primary toggle component](https://www.patternfly.org/v4/documentation/react/components/dropdown#primary-toggle).

The proposal is about styling the Primary toggle as a button instead of as a dropdown toggle:
_Current Primary toggle styling_
<img width="158" alt="Screenshot 2020-02-05 15 55 05" src="https://user-images.githubusercontent.com/2865173/73852677-e6bc8a00-482f-11ea-9cad-4d0bad730b56.png">
_Proposed styling (as found in some [existing mockups](https://openshift.github.io/openshift-origin-design/designs/administrator/future-openshift/bulk-actions/))_
<img width="126" alt="Screenshot 2020-02-05 15 56 59" src="https://user-images.githubusercontent.com/2865173/73852836-25eadb00-4830-11ea-93e3-609cc2658be8.png">

The rationale is that the Primary toggle is a button with dropdown capabilities, rather than a variation on the style of a dropdown toggle.

My feeling is that, when styled as a button, the Primary toggle would be perceived more intuitively like an instant primary/secondary action, mostly in contexts where other dropdown toggles already exist:
<img width="501" alt="Screenshot 2020-02-05 15 44 49" src="https://user-images.githubusercontent.com/2865173/73853023-7b26ec80-4830-11ea-830c-67c2acbfad38.png">
<img width="508" alt="Screenshot 2020-02-05 15 44 34" src="https://user-images.githubusercontent.com/2865173/73853036-7feba080-4830-11ea-8408-34522fb47ed0.png">
Note – I haven't run any user testing, so I don't have data to prove this.

Happy to hear others' thoughts and discuss more about this.

**Comment by mcoker** [comment] 2020-02-18 21:45
cc @mcarrano

**Comment by mcarrano** [comment] 2020-02-18 22:29
Agree that we should do this. Just a matter of getting this on the roadmap. 

cc @LHinson

**Comment by gdoyle1** [comment] 2020-05-06 15:41
Would be great to get this in as it would be super useful for OpenShift as well! We're doing a work around where we present bulk actions in a basic dropdown menu until items are selected - that basic dropdown menu then becomes a primary toggle. Agreed with @cntlsn that the primary toggle should look more like a button!

**Comment by mcarrano** [comment] 2020-07-29 15:12
I'm pretty sure this is a duplicate of https://github.com/patternfly/patternfly/issues/3258 that is already on the roadmap. @mcoker can you confirm and close if that's the case?

**Comment by mcoker** [comment] 2020-08-06 22:15
Yep, looks like a dupe of #3258.

**Closed by mcoker** 2020-08-06 22:15 UTC
