### ISSUE TITLE
Update notification drawer styles and examples

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2992] opened 2020-04-21 15:35 UTC
Want to update the notification drawer component as follows:

* Make ability to display read/unread notifications an optional feature.
* Add optional filtering
* Simplify styling of notification items.

See revised designs here: https://marvelapp.com/4f0341a

cc: @mcoker @LHinson

**Comment by mcoker** [comment] 2020-06-22 22:58
dupe of https://github.com/patternfly/patternfly/issues/2993

**Closed by mcoker** 2020-06-22 22:58 UTC
Labels: css, enhancement
