### ISSUE TITLE
An enabled text box with partially non-editable content 

### ISSUE THREAD

**Issue by yannnz** [patternfly/patternfly#3171] opened 2020-06-10 15:25 UTC
Will patternfly consider about having an enabled text box with partially non-editable content? 

The use case I listed in the screenshot is to have parent parameters displayed as non-editable content inside the text box of the child parameter (the gray-colored content with "/"is the parent parameters ).  And the user can input or edit the child parameter following the parent parameters.
<img width="602" alt="Screen Shot 2020-06-10 at 11 19 37 PM" src="https://user-images.githubusercontent.com/10469467/84286205-f860c600-ab70-11ea-9708-53c0fecaecfd.png">

.

**Comment by mcoker** [comment] 2020-06-23 22:17
cc @mcarrano @mceledonia wdyt?

**Comment by mcarrano** [comment] 2020-06-24 12:58
@mcoker can we achieve this with the standard form control input we are using or would this require a custom input?

**Comment by mcoker** [comment] 2020-06-24 18:54
It would need to be a custom input to be able to style the contents that way.

**Comment by anukritijha** [comment] 2020-08-19 11:03
@mcarrano @mcoker Just wanted to check, if this would be supported by PF in any of the future releases?

**Comment by mcarrano** [comment] 2020-08-19 13:36
@anukritijha @yannnz This will need to be added to our roadmap. Is there a specific project need or timeframe you are looking for? This will help us prioritize. Thanks.

**Comment by anukritijha** [comment] 2020-08-19 14:02
@mcarrano This was intended for AMQ Online's 2.0 release, however, due to the recent change is strategy, we don't have a milestone yet. So, this is not a priority as of now. I will update once I have more clarity on the plan.

**Comment by mcarrano** [comment] 2020-08-19 18:46
OK. I will queue this up to add to our roadmap, but will probably fall into next year. Let me know if you need it sooner than that.

**Comment by mcoker** [comment] 2021-07-16 16:09
@anukritijha sorry for the delay on this issue. There hasn't been any activity since last year - I just wanted to check and see if this enhancement is still needed?

**Comment by anukritijha** [comment] 2021-07-19 05:54
@mcoker This enhancement may not be needed anytime in the near future, so we can close this issue.

**Closed** 2021-07-19 16:04 UTC
Labels: design approved
