### ISSUE TITLE
Form group: label info misaligned

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#6648] opened 2024-05-14 18:03 UTC
a `.pf-v6-c-form__group` inside a `.pf-v6-c-form .pf-m-horizontal`

when a `.pf-v6-c-form__group-label-info` is passed to the form group on a horizontal form, the label is wrapping. It should probably go under the label? Also, whenever there is helper text and a label-info, the vertical alignment of the label also seems off. It seems to be bottom aligned.

![Screenshot 2024-05-14 at 2 01 59 PM](https://github.com/patternfly/patternfly/assets/26305082/61f64e66-6ecf-43a0-9278-f9a027946555)

Reported by Ansible

**Comment by mattnolting** [comment] 2024-05-15 17:38
closing, duplicate of #6032

**Closed by mattnolting** 2024-05-15 17:38 UTC
Labels: v6 alpha bug
