### ISSUE TITLE
Borderless, compact and expandable table borders

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#3650] opened 2020-11-09 16:37 UTC
During react implementation of composable tables, `.pf-m-no-border-rows`, when added to `.pf-c-table.pf-m-compact.pf-m-expandable` has no effect. 

Looks like we need to increase specificity of which borders are hidden:  https://github.com/patternfly/patternfly/blob/master/src/patternfly/components/Table/table.scss#L875

**Comment by mcoker** [comment] 2020-11-09 18:55
I believe this was by design. @mceledonia @mcarrano wdyt?

https://www.patternfly.org/v4/components/table/html#usage-5

> `.pf-m-no-border-rows` | `.pf-c-table.pf-m-compact` | Modifies to remove borders between rows. Note: Can not be used with `.pf-m-expandable.`

**Comment by mcarrano** [comment] 2020-11-09 21:47
Yes, that seems to be the case @mcoker . Although I can't exactly recall why. It may be that it would be difficult to tell where the row boundaries are if that were the case? Is there a problem with the current approach?

**Comment by jschuler** [comment] 2020-11-10 15:05
@mcarrano Also cannot make the regular (non-compact) table borderless. Curious if this is also by design. The answers will dictate the API

**Comment by jschuler** [comment] 2020-11-10 16:51
Sounds like we can make `.pf-m-no-border-rows` more universal to all variants (default, compact, expandable, compound-expandable?), and I believe we won't need the `.pf-m-expandable` modifier on `.pf-c-table` anymore as well since it's purpose was just to disallow removal of borders in specific variations.

**Comment by mcoker** [comment] 2020-12-02 15:16
closed via https://github.com/patternfly/patternfly/pull/3691

**Closed by mcoker** 2020-12-02 15:16 UTC
