### ISSUE TITLE
Spike: investigate solutions for displaying icons in validated text inputs

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly#2702] opened 2020-02-12 13:59 UTC
**Describe the issue. What is the expected and unexpected behavior?**

Setting the validated field on a `TextInput` should show the appropriate icon to the far right per Patternfly core:

https://pf4.patternfly.org/documentation/core/components/form#help-text
![image](https://user-images.githubusercontent.com/11633780/74340996-fe869780-4d74-11ea-811e-0b6384c3eed8.png)

Instead it is not showing:

https://patternfly-react.surge.sh/documentation/react/components/form#validated
![image](https://user-images.githubusercontent.com/11633780/74341455-c03da800-4d75-11ea-90ce-fad6fa01ed5d.png)

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

Bug, no work around.

**What is your product and what release version are you targeting?**

Openshift Console, likely 4.5

cc @serenamarie125 @christianvogt

**Comment by mcoker** [comment] 2020-02-12 16:08
Looks like this is a CSS problem and only occurs when the form control's value is selected from autofill. Chrome is applying a `background` with `!important`, that overrides the background image we use for the icon.

**Comment by mcoker** [comment] 2020-02-17 17:01
A potential fix - https://codepen.io/mcoker/pen/rNVegEX

**Comment by jeff-phillips-18** [comment] 2022-04-06 13:41
@mcoker The work around you had no longer works. You can see the problem in https://codesandbox.io/s/autofill-background-issues-2wrejy?file=/src/styles.css

Do you have any suggestions?

**Comment by jerolimov** [comment] 2022-04-06 13:46
This is the style that is now added by Chrome:

![image](https://user-images.githubusercontent.com/139310/161988652-8362f22b-68bb-4c34-8aa3-f01dfe0f3bfc.png)

Changing the CSS rules from the previous fix - https://codepen.io/mcoker/pen/rNVegEX from `-webkit-autofill` to `-internal-autofill-selected` unfortunately doesn't work.

**Comment by srambach** [comment] 2022-05-16 19:43
As noted above, known solutions trying to maintain a background image on an input while Chrome autocomplete removes it have all stopped working. At this point, the only known solution is to restructure the HTML to add the image as a separate element rather than a background image on the input. 
For now, we'll add a note on the form field component and mark this to be fixed in a breaking change.

**Comment by nicolethoen** [comment] 2022-11-16 15:42
The TextInput was designed for use in a form element. The TextInputGroup was not - and does not currently have a concept of validation states built into it.

So the decision remains - do we want to move validation out of the TextInput and into the TextInputGroup, or just update the TextInput to behave a bit more like a TextInput.

**Comment by nicolethoen** [comment] 2023-04-18 21:12
This will be fixed by https://github.com/patternfly/patternfly/issues/5469

**Closed** 2023-05-15 20:17 UTC
Labels: Spike, p1, lg
