### ISSUE TITLE
File Upload -- Multiple long file name support

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly#4660] opened 2022-02-03 20:24 UTC
As identified in https://github.com/patternfly/patternfly/pull/4548#issuecomment-984155549 the multiple file upload status items develop some alignment issues with file names that are too long.

One suggested approach was to truncate the file names if needed, but based on my attempt to do so (by wrapping the title in a Truncate component) there are issues with that approach as well that I think will need a fix on the core side.

Result from my attempt to truncate the file title in the horizontal version of the multiple file upload component:
![Screen Shot 2022-02-03 at 2 03 09 PM](https://user-images.githubusercontent.com/7115053/152422853-4f381b27-aca8-42dd-acbf-077e1f7bf0c9.png)

**Comment by srambach** [comment] 2022-05-03 14:37
The truncate component seems to work here when put in on core. The width of the file upload will expand as needed to the limit of its container. This is consistent with our convention of components filling their container. We could add a max-width, but this would break that convention. If the width of the container is limited, the truncation happens as expected.

Long filenames without truncation applied wrap and do not cause overflow. I can't reproduce the overflow as shown above, so maybe something has fixed that in the interim.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/19825616/166474179-7624345c-d009-4ed0-9574-d1f12c0a82d6.png">

**Comment by wise-king-sullyman** [comment] 2022-05-04 18:54
I'm also not seeing the overflow behavior that I saw before for some reason.

**Comment by srambach** [comment] 2022-05-11 19:11
Closing this issue because it cannot be reproduced.

**Closed by srambach** 2022-05-11 19:11 UTC
