### ISSUE TITLE
Add Tabular Font to Dynamic Components

### ISSUE THREAD

**Issue by kelseamann** [patternfly/patternfly#5476] opened 2023-04-12 18:38 UTC
The tabular font face is a variant of Red Hat VF that applies “monospace” typesetting to only the numbers in a given component. This variant evenly distributes digits on the screen, making them all the same width. The proposal is to change any Patternfly components that fit the criteria to default to the tabular variant of Red Hat VF. 

Use a tabular font face (generally) when the component requires the user to quickly scan data for a change in one digit.
Numbers are changing dynamically on screen (typically counting)
Comparable numbers are stacked directly on top of each other

When proportional spacing is used, it leads to “jumpy” changing in the width of the number, and the eye is distracted by too much movement.

Comparison (below) of tabular vs proportional fonts in the slider.
![slider tabular](https://user-images.githubusercontent.com/91503095/231553256-1303ac87-294e-45ff-af48-7b5f59d3c49c.gif)

![slider final zoomed](https://user-images.githubusercontent.com/91503095/231553278-6fb8d924-4dfb-43c5-a5c0-91ec4b48595d.gif)

Where numbers change dynamically
Calendar month subtext https://www.patternfly.org/v4/components/calendar-month (looks already implemented?)
Progress bar https://www.patternfly.org/v4/components/progress
Slider[ https://www.patternfly.org/v4/components/slider](https://www.patternfly.org/v4/components/slider)
Time picker https://www.patternfly.org/v4/components/time-picker
Timestamp https://www.patternfly.org/v4/components/timestamp
Where numbers are stacked
Table https://www.patternfly.org/v4/components/table

**Comment by nicolethoen** [comment] 2023-04-25 19:45
In many cases, this may be something that can be addressed by the addition of a class. We may just need to expand our documentation and update our examples to use it.

We also have a way to opt into the tabular font everywhere in an app numbers are used.

**Comment by nicolethoen** [comment] 2023-04-25 19:47
The implementation would differ component by component. Some component's CSS could be updated to use tabular font all the time.

**Comment by kelseamann** [comment] 2023-04-26 13:21
@nicolethoen maybe @mcoker could help with this. He and I talked briefly on Slack before I introduced this issue, where he mentioned that there is an existing global class called .pf-m-tabular-nums which will make an object and any nested children use tabular numbers.

**Comment by andrew-ronaldson** [comment] 2024-05-15 12:15
Linking this [issue](https://github.com/patternfly/patternfly/issues/5308) for additional context.

**Comment by srambach** [comment] 2024-08-13 18:31
After chatting with @lboehling on this and some additional investigation:

- Calendar month subtext https://www.patternfly.org/v4/components/calendar-month This is using `<pre>` and isn't actually part of the component.

- Progress bar https://www.patternfly.org/v4/components/progress - the measure seems like a legitimate place to build in tabular numbers as part of the component. :white_check_mark:

- Slider[ https://www.patternfly.org/v4/components/slider](https://www.patternfly.org/v4/components/slider) - the example shown in the issue is just text added separately from the actual component. I can apply the modifier for the example. @lboehling called out the [tooltip on the slider](https://staging-v6.patternfly.org/components/slider#continuous). I'll look at adding it there but as currently implemented, there will still be a width change when the value has one decimal place vs 2 (e.g. 1.53 vs 1.5)

- Time picker https://www.patternfly.org/v4/components/time-picker (and date picker) - since these are user inputs, it doesn't seem like forcing them to tabular numbers has a great benefit. And unless the leading zero is enforced always, multiple date/times still would not line up with each other.

- Timestamp https://www.patternfly.org/v4/components/timestamp - this often/always contains non-numeric characters, so it creates a mix of styles that looks odd. The modifier could be added to a wrapper if desired.

Where numbers are stacked
- Table https://www.patternfly.org/v4/components/table - Tabular numbers might be useful in some cases, as would [right aligned columns](https://github.com/patternfly/patternfly/issues/6572) but perhaps as a modifier only. We do have a modifier `.pf-m-tabular-nums` to set something to use tabular text. I'm looking into where the best place to document this would be.

Regarding the related issue of slashed zeros and readability:
Per @lboehling: I also talked to Ryan from brand and it looks like they do plan to get rid of the slashed zero in the font based on some talks with the RHEL BU too.

**Comment by mcoker** [comment] 2024-08-20 19:05
closed by https://github.com/patternfly/patternfly/pull/6985

**Closed by mcoker** 2024-08-20 19:05 UTC
Labels: enhancement, Feature, breaking change :boom:, pinned, PF6
