### ISSUE TITLE
Bug - Truncate - unwanted gaps with position "middle"

### ISSUE THREAD

**Issue by mvollmer** [patternfly/patternfly#6261] opened 2024-01-30 16:36 UTC
This:

```
<Truncate content="llllllllllllllllllllll"
          position="middle"
          trailingNumChars={4} />
 ```

produces this:

![image](https://github.com/patternfly/patternfly/assets/3228183/05957757-0547-4dac-a640-de78b8d21bfd)

Note the extra gap before the last four characters.

**Comment by mvollmer** [comment] 2024-02-08 12:40
"Needs info"?

**Comment by mcoker** [comment] 2024-02-08 15:35
Hey @mvollmer, that just means I'm going to look into what the root cause is, and based on that make sure the issue is in the right repo and we have all the info we need to add it to a sprint and push a fix.

**Comment by mvollmer** [comment] 2024-02-09 07:45
> Hey @mvollmer, that just means I'm going to look into what the root cause is, and based on that make sure the issue is in the right repo and we have all the info we need to add it to a sprint and push a fix.

Excellent, thanks! I was afraid you need something from me still.

**Comment by mcoker** [comment] 2024-06-11 19:27
closed by https://github.com/patternfly/patternfly/pull/6733

**Closed by mcoker** 2024-06-11 19:27 UTC
Labels: bug, pinned
