### ISSUE TITLE
Chrome "Save to Pocket" extension makes radio buttons invisible

### ISSUE THREAD

**Issue by cben** [patternfly/patternfly#4504] opened 2021-10-27 12:41 UTC
**Describe the issue. What is the expected and unexpected behavior?**
[Save to Pocket](https://chrome.google.com/webstore/detail/save-to-pocket/niloccemoadcdkdjlinkgdfekeahmflj) is quite popular Chrome extension (2 million users).  I noticed it makes PF radio buttons invisible:
![Ekrankopio de 2021-10-27 15-29-26](https://user-images.githubusercontent.com/273688/139066395-8f38f333-8d7c-411d-89dd-09aba8dccfa6.png)

I guess it should be reported & fixed at https://github.com/Pocket/extension-save-to-pocket — that extension doesn't intend to affect site rendering — but don't have time now, so reporting here as frankly we're more interested in fix ;-)

I'm seeing this CSS:
![Ekrankopio de 2021-10-27 15-37-50](https://user-images.githubusercontent.com/273688/139067355-a688f0fd-cc4b-4a2f-83a6-b1636e49367d.png)

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
Install extension, visit https://patternfly-react.surge.sh/components/radio/
I'm on Chrome Version 95.0.4638.54 (Official Build) (64-bit), fedora 35, wayland.

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
bug, though arguably in the extension.

**What is your product and what release version are you targeting?**

**Comment by srambach** [comment] 2022-01-04 21:53
Hi @cben, are you still seeing this issue on your configuration? I am unable to reproduce it with Chrome Version 97.0.4692.71 (Official Build) (x86_64), macOS Big Sur, Save to Pocket 4.0.3

**Comment by srambach** [comment] 2022-01-10 15:23
Hey @cben, I'm going to move this over to the parking lot - if you are able to reproduce it I'd love to get some more information from you, and otherwise feel free to close the issue.  Thanks!

**Closed** 2022-04-19 01:35 UTC
Labels: wontfix
