### ISSUE TITLE
Table - add min/max height to OuterScrollContainer

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#5019] opened 2022-08-03 14:59 UTC
**Is this a new component or an extension of an existing one?**
Composable table

**Describe the feature**
https://github.com/patternfly/patternfly-react/issues/7425#issuecomment-1198249738

**Comment by mcoker** [comment] 2022-08-19 21:44
@mattnolting is this a dupe of https://github.com/patternfly/patternfly/issues/5038?

**Comment by mattnolting** [comment] 2022-08-19 23:07
@mcoker yep, closing

**Closed** 2022-08-19 23:07 UTC
Labels: Feature
