### ISSUE TITLE
Incorrect padding for compact table

### ISSUE THREAD

**Issue by ai212983** [patternfly/patternfly#955] opened 2018-11-19 20:15 UTC
Not sure if its subticket of #809, but in compact table topmost and bottommost rows has extra padding with inconsistent values (not `tr`s themselves, but their `td`s). Row background highlighting looks broken because of this.

**Comment by mcoker** [comment] 2020-08-07 19:25
This should be fixed, we recently re-worked the padding in all tables in the v4 release, and the tables were reviewed and approved by design.

**Closed** 2020-08-07 19:30 UTC
