### ISSUE TITLE
Custom icons - determine process for teams creating custom icons

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly#2353] opened 2019-10-09 14:55 UTC
Teams want to introduce custom icons to bring into the PatternFly React library. We should determine:

- What is the process for bringing in custom icons? Is a designer involved?
- What are the requirements for a custom icon? Ex. where did it originate?

**Comment by mcoker** [comment] 2020-08-13 13:22
dupe of https://github.com/patternfly/patternfly/issues/2335

**Closed by mcoker** 2020-08-13 13:22 UTC
