### ISSUE TITLE
Table - text align right modifier

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6934] opened 2024-07-30 15:17 UTC
Table cells need a standard method to align text to `left` (default), `center`, and `right`. We currently have only `pf-m-center`

- [ ] Add modifier - `left`
- [ ] Add modifier - `right`

**Comment by mcoker** [comment] 2024-07-31 23:04
Dupe of https://github.com/patternfly/patternfly/issues/6572

**Closed by mcoker** 2024-07-31 23:04 UTC
Labels: Feature
