### ISSUE TITLE
Dropdown (PF4): Caret is not properly aligned

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#2715] opened 2020-02-12 11:24 UTC
On our codebase it looks like this: (notice the misaligned caret)

![Screen Shot 2020-02-12 at 12 15 33](https://user-images.githubusercontent.com/14921356/74330140-6ea31680-4d91-11ea-83ef-260c89073aa5.png)

But it should looks like this:
![Screen Shot 2020-02-12 at 12 03 25](https://user-images.githubusercontent.com/14921356/74330079-4f0bee00-4d91-11ea-901b-0a9df74d25b4.png)

If you notice in the first screenshot the caret if off by some pixels. This is probably happening due to fonts (we use Red Hat font, PF docs do not) and or the browser testing this. (the screenshots are from Firefox 72.0.2)
The caret needs to be aligned to the center and not use an arbitrary font-based (& OS & browser influenced) offset from the top.

In our codebase the designers fixed that with the following snippet:
``` css
/* Fix alignment for icons inside of dropdown toggle (& split) buttons */
/* Part 1 of 2 */
.pf-c-dropdown__toggle {
  align-items: stretch;
  /* PF4 uses align-items: center here; stretch (the default) is what we need. */
}

/* Align the icons inside of the toggle. Part 2 of 2 */
.pf-c-dropdown__toggle-button {
  display: flex;
  align-items: center;
}

```

Note: I am not sure if this issue should be tracked here or better in the patternfly-next repository, please move it if it's wrong here.

**Comment by KKoukiou** [comment] 2020-07-29 07:19
Undo bot 'wontfix'

**Comment by mcoker** [comment] 2020-08-24 22:16
Hey @garrett @KKoukiou since users can pass any HTML permissible in a `<button>` there, applying `display: flex;` may be a breaking change as it would change the layout of the toggle button's children. We are also now using [RedHatText](https://github.com/patternfly/patternfly/blob/1a1a1a84c6e1efaa65b1b872c0aa306755b868fb/src/patternfly/sass-utilities/scss-variables.scss#L193) both in PatternFly and in the documentation.

Are you able to reproduce the problem and can you share that with me so I can look into it more?

**Comment by garrett** [comment] 2020-08-31 12:04
@mcoker: Thanks for following up!

It looks like changes in PF, especially adopting the RedHatText font, have helped to fixed the alignment, so I've sent a PR to drop our local override. (When that lands, it should close this bug too.)

I've assigned @KKoukiou as a reviewer. Hopefully she agrees and then this should be resolved.

**Closed** 2020-08-31 15:49 UTC
