### ISSUE TITLE
pf-c-select: the minified css results in wrong border for the select

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#4028] opened 2021-04-26 14:58 UTC
/bug

!NOTE: this issue appears only when using the minified version of the code, when consuming PF with NODE_ENV=development this works as expected!

A recent PF update (presumably some upload from from April) broke the Select component, in a way that it does not have borders. 

In the screenshot below, the operating system field, is actually a typeahead Select, and used to have border around. A recent PF update removed the border.

I cannot reproduce the issue on the PF4 documentation page, but as I said this is also an issue for us only when compiling with NODE_ENV=production. Maybe the docs consume the dev build?

In the screenshot one can see the problematic CSS in the inspector. The border-width is somehow expanded into border-{top, bottom, left, right} and is using however the initial variable for BorderWidth.

I guess it's some error from the minifiers or unexpected usage of the border rule expansion. I can also locate the problematic code in the @patternfly/patternfly repo, when compiling the source, and checking the dist/patternfly.min.css file.

 
![Screenshot from 2021-04-26 16-29-09](https://user-images.githubusercontent.com/14921356/116103341-c9334480-a6af-11eb-81ed-cff984828424.png)

**Comment by redallen** [comment] 2021-04-26 15:01
Duplicate of https://github.com/patternfly/patternfly-react/issues/5650. This needs to be fixed upstream in `cssnano`, PatternFly isn't doing anything wrong.

**Closed by redallen** 2021-04-26 15:01 UTC
