### ISSUE TITLE
<DescriptionList> isFillColumns has unexpected side effect

### ISSUE THREAD

**Issue by ChrisLee5000** [patternfly/patternfly#6767] opened 2024-06-11 03:56 UTC
**Please describe the issue**

When using the isFillColumns option for <DescriptionList>, the items are reordered unexpectedly. The expected behaviour is the items stay in the same order but with columns expanding to the container width.

**Are there visuals for this issue? Please provide screenshots**

https://staging-v6.patternfly.org/components/description-list/react/column-fill/

In this example, the 2nd element "Namespace: mary-test" is in the wrong order. Edit the example, removing isFillColumns, and you will see the correct ordering.

**Could you point to a branch or draft PR where this issue exists? Please provide a link to the code**

**Any other information?**

**Comment by srambach** [comment] 2024-06-27 20:27
Hi @ChrisLee5000 
It looks like `isFillColumns` is working as intended - which is to say that modifier causes the description list to fill down the first column and then down the next and so on, balancing the columns. The name may be a bit misleading, but actually has nothing to do with the width of the columns.

You can see the description in our [usage section.](https://staging-v6.patternfly.org/components/description-list/#descriptionlist) and it might be a little more clear in the [HTML docs](https://staging-v6.patternfly.org/components/description-list/html#usage)

If you have a design of the layout you are trying to achieve, feel free to share and I might be able to make a suggestion.

**Comment by ChrisLee5000** [comment] 2024-06-27 21:48
Thanks @srambach for the clarification. Also, I like where the DescriptionList is going in V6! I find this a very useful component for laying out lots of small pieces of information.

**Comment by srambach** [comment] 2024-06-28 13:56
@ChrisLee5000 Great to hear! I'll close this issue then. As always, let us know if you have comments or questions.

**Closed by srambach** 2024-06-28 13:56 UTC
Labels: v6 alpha bug
