### ISSUE TITLE
Bug - Modal - header padding broken when scrolling

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#6304] opened 2024-02-12 21:19 UTC
Reported by ansible

reproducible in PF docs: https://www.patternfly.org/components/modal#scrollable-modals

The modal header padding is off:
![image (9)](https://github.com/patternfly/patternfly-react/assets/26305082/c9d1e113-1695-4c34-992c-e6da04005c51)

And the dark mode makes the padding issue even more obvious:
![Screenshot 2024-02-12 at 3 54 45 PM](https://github.com/patternfly/patternfly-react/assets/26305082/78c5f21c-c85a-4a5f-933c-2082665415a9)

**Comment by mcoker** [comment] 2024-02-13 00:46
cc @lboehling @andrew-ronaldson - wdyt? There is a core demo that shows the issue, too,  (https://www.patternfly.org/components/modal/html-demos#scrollable-content) and the issue is in penta as well

**Comment by nicolethoen** [comment] 2024-04-04 18:26
We've determined that adding more padding around the heading will cause layout shifts for consumers. Since it's been this way for so long, most consumer have probably already written a fix to address. Rather than risk introducing a breaking change or risk breaking existing consumer overrides, this issue will be addressed in PatternFly 6.

**Comment by evwilkin** [comment] 2024-05-04 13:51
Suggestions:

<details>
  <summary>Change `padding-top` to `margin-top` on `class="pf-v6-c-modal-box__body"`</summary>

![Image](https://github.com/patternfly/patternfly/assets/8651509/4c0d04e0-55a0-4bae-8295-3c2c28100240)
![Image](https://github.com/patternfly/patternfly/assets/8651509/a77ccd0c-a81b-4881-998a-3914b1369501)

</details>

<details>
  <summary>Remove `padding-top` from `class="pf-v6-c-modal-box__body"` and instead add it as `padding-bottom` to the modal header</summary>

![Image](https://github.com/patternfly/patternfly/assets/8651509/26f92eb9-c7a9-4946-bea5-1b2ace734cdd)

</details>

**Comment by mcoker** [comment] 2024-05-31 21:20
closed by https://github.com/patternfly/patternfly/pull/6699

**Closed by mcoker** 2024-05-31 21:20 UTC
Labels: bug, PF6
