### ISSUE TITLE
DataList customizable breakpoints

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly#2108] opened 2019-07-25 21:05 UTC
Currently, DataList has static breakpoints defined. Like many apps, we have a need over in Syndesis to be able to customize these breakpoints to account for various sized content at various viewport dimensions so that we can optimize the layout and take full advantage of the available space. Can we add this as a feature?

**Comment by rachael-phillips** [comment] 2019-07-29 13:57
Hi @seanforyou23 what is your timeline like for when you will need this?

**Comment by seanforyou23** [comment] 2019-07-30 18:30
@rachael-phillips it's not a blocking issue for me, however, we do have a need for it in a few projects I work on. I don't have any specific target date, just on my wishlist for when it's practical. I believe this was mentioned recently as a pain point in our public slack also, which was my motivation for posting this issue. Does that help? Let me know if you need more info!

**Comment by mcoker** [comment] 2020-08-12 15:56
dupe of https://github.com/patternfly/patternfly/issues/3228, working on that this milestone!

**Closed by mcoker** 2020-08-12 15:56 UTC
