### ISSUE TITLE
Proposal: Cascade layers 

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6506] opened 2024-04-02 14:51 UTC
# TLDR

Cascade layers (related to [6647](https://github.com/patternfly/patternfly/issues/6647)) would solve a significant amount of specificity conflicts and enable users to efficiently them their apps.

> Placeholder issue for adding basic cascade layer support to patternfly for penta. It would be good to even get a base layer setup going that we can build upon. Something like this maybe?
>
> base styles (reset/normalize stuff)
> component/layout styles
> utilities
> user overrides
>
> But with the theming in penta, we could do a lot of cool stuff with the theme overrides! @srambach has a codepen with some fun goodies for reference - https://codepen.io/srambach/pen/bGOMBNW

**Comment by srambach** [comment] 2024-04-10 14:36
Related issue https://github.com/patternfly/patternfly/issues/6433

**Comment by srambach** [comment] 2024-05-28 19:59
Closing because it's a duplicate of #6433

**Closed by srambach** 2024-05-28 19:59 UTC
Labels: Feature, PF6, Post v6
